-- Create app_settings table
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_locked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default row if not exists
INSERT INTO public.app_settings (id, login_locked)
SELECT 1, FALSE
WHERE NOT EXISTS (SELECT 1 FROM public.app_settings WHERE id = 1);

-- Enable RLS
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Policies for app_settings
DROP POLICY IF EXISTS "Allow public read access" ON public.app_settings;
CREATE POLICY "Allow public read access" ON public.app_settings
    FOR SELECT TO public USING (true); -- Everyone needs to know if locked

DROP POLICY IF EXISTS "Allow admin update" ON public.app_settings;
CREATE POLICY "Allow admin update" ON public.app_settings
    FOR UPDATE TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );

-- Add is_generating to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_generating BOOLEAN DEFAULT FALSE;

-- Ensure users can update their own is_generating status
-- Assuming there is already a policy for updating own profile, if not, we rely on existing ones or add:
-- (We'll safely add one that doesn't conflict if possible, but 'profiles' usually has one. 
--  To be safe, we'll let existing policies handle it or the user can check.)
